.PHONY: ALL

ALL: XSqrt_reg.vo XRtrigo_def.vo XRgeom.vo XReals.vo XRanalysis1.vo XRminmax.vo XROrderedType.vo XRRle_refl.vo XRbasic_fun.vo XRtrigo_fun.vo XRIneq.vo XRList.vo XRanalysis5.vo XRpow_def.vo XSplitAbsolu.vo XSeqProp.vo XPSeries_reg.vo XRiemannInt.vo XRnumbers.vo XSeqSeries.vo XRRlt_irrefl.vo XRsigma.vo XRtrigo_reg.vo XRtopology.vo XR_sqr.vo XAltSeries.vo XRcomplete.vo XRanalysis2.vo XCos_rel.vo XExp_prop.vo XSplitRmult.vo XRprod.vo XRfunctions.vo XDiscrR.vo XRNlink.vo XArithProp.vo XNewtonInt.vo XRatan.vo XRlimit.vo XRderiv.vo XRanalysis3.vo XPartSum.vo XIntegration.vo XRcompleteness.vo XR_Ifp.vo XCos_plus.vo XAlembert.vo XAllReals.vo XRaxioms.vo XRtrigo.vo XRsqrt_def.vo XRpower.vo XCauchy_prod.vo XRZlink.vo XBinomial.vo XRbase.vo XMachin.vo XRanalysis.vo XR_sqrt.vo XRiemannInt_SF.vo XRlogic.vo XRanalysis_reg.vo XRtrigo_alt.vo XMVT.vo XRanalysis4.vo XRdefinitions.vo XRseries.vo XRtrigo_calc.vo XRtrigo1.vo

XAlembert.vo : XAlembert.v  XRbase.vo XRfunctions.vo XRseries.vo XSeqProp.vo XPartSum.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XAlembert.v

XAllReals.vo : XAllReals.v  XReals.vo XRlogic.vo XRminmax.vo
	 C:\Coq\bin\coqc XAllReals.v

XAltSeries.vo : XAltSeries.v  XRbase.vo XRfunctions.vo XRseries.vo XSeqProp.vo XPartSum.vo
	 C:\Coq\bin\coqc XAltSeries.v

XArithProp.vo : XArithProp.v  XRbase.vo XRbasic_fun.vo
	 C:\Coq\bin\coqc XArithProp.v

XBinomial.vo : XBinomial.v  XRbase.vo XRfunctions.vo XPartSum.vo
	 C:\Coq\bin\coqc XBinomial.v

XCauchy_prod.vo : XCauchy_prod.v  XRbase.vo XRfunctions.vo XRseries.vo XPartSum.vo
	 C:\Coq\bin\coqc XCauchy_prod.v

XCos_plus.vo : XCos_plus.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_def.vo XCos_rel.vo
	 C:\Coq\bin\coqc XCos_plus.v

XCos_rel.vo : XCos_rel.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_def.vo
	 C:\Coq\bin\coqc XCos_rel.v

XDiscrR.vo : XDiscrR.v  XRIneq.vo
	 C:\Coq\bin\coqc XDiscrR.v

XExp_prop.vo : XExp_prop.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XRanalysis1.vo XPSeries_reg.vo
	 C:\Coq\bin\coqc XExp_prop.v

XIntegration.vo : XIntegration.v  XNewtonInt.vo XRiemannInt_SF.vo XRiemannInt.vo
	 C:\Coq\bin\coqc XIntegration.v

XMachin.vo : XMachin.v  XRbase.vo XRtrigo1.vo XRanalysis_reg.vo XRfunctions.vo XAltSeries.vo XRseries.vo XSeqProp.vo XPartSum.vo XRatan.vo
	 C:\Coq\bin\coqc XMachin.v

XMVT.vo : XMVT.v  XRbase.vo XRfunctions.vo XRanalysis1.vo XRtopology.vo
	 C:\Coq\bin\coqc XMVT.v

XNewtonInt.vo : XNewtonInt.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XRanalysis.vo
	 C:\Coq\bin\coqc XNewtonInt.v

XPartSum.vo : XPartSum.v  XRbase.vo XRfunctions.vo XRseries.vo XRcomplete.vo
	 C:\Coq\bin\coqc XPartSum.v

XPSeries_reg.vo : XPSeries_reg.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRanalysis1.vo XMVT.vo
	 C:\Coq\bin\coqc XPSeries_reg.v

XRanalysis.vo : XRanalysis.v  XRbase.vo XRfunctions.vo XRtrigo.vo XSeqSeries.vo XRanalysis1.vo XRanalysis2.vo XRanalysis3.vo XRtopology.vo XMVT.vo XPSeries_reg.vo XExp_prop.vo XRtrigo_reg.vo XRsqrt_def.vo XR_sqrt.vo XRtrigo_calc.vo XRgeom.vo XRList.vo XSqrt_reg.vo XRanalysis4.vo XRpower.vo XRanalysis_reg.vo
	 C:\Coq\bin\coqc XRanalysis.v

XRanalysis1.vo : XRanalysis1.v  XRbase.vo XRfunctions.vo XRlimit.vo XRderiv.vo
	 C:\Coq\bin\coqc XRanalysis1.v

XRanalysis2.vo : XRanalysis2.v  XRbase.vo XRfunctions.vo XRanalysis1.vo
	 C:\Coq\bin\coqc XRanalysis2.v

XRanalysis3.vo : XRanalysis3.v  XRbase.vo XRfunctions.vo XRanalysis1.vo XRanalysis2.vo
	 C:\Coq\bin\coqc XRanalysis3.v

XRanalysis4.vo : XRanalysis4.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XRanalysis1.vo XRanalysis3.vo XExp_prop.vo XMVT.vo
	 C:\Coq\bin\coqc XRanalysis4.v

XRanalysis5.vo : XRanalysis5.v  XRbase.vo XRanalysis_reg.vo XRfunctions.vo XRseries.vo XRiemannInt.vo XSeqProp.vo
	 C:\Coq\bin\coqc XRanalysis5.v

XRanalysis_reg.vo : XRanalysis_reg.v  XRbase.vo XRfunctions.vo XRtrigo1.vo XSeqSeries.vo XRanalysis1.vo XRanalysis2.vo XRanalysis3.vo XRtopology.vo XMVT.vo XPSeries_reg.vo XExp_prop.vo XRtrigo_reg.vo XRsqrt_def.vo XR_sqrt.vo XRtrigo_calc.vo XRgeom.vo XRList.vo XSqrt_reg.vo XRanalysis4.vo XRpower.vo
	 C:\Coq\bin\coqc XRanalysis_reg.v

XRatan.vo : XRatan.v  XRbase.vo XPSeries_reg.vo XRtrigo1.vo XRanalysis_reg.vo XRfunctions.vo XAltSeries.vo XRseries.vo XSeqProp.vo XRanalysis5.vo XSeqSeries.vo XPartSum.vo
	 C:\Coq\bin\coqc XRatan.v

XRaxioms.vo : XRaxioms.v  XRdefinitions.vo XRZlink.vo
	 C:\Coq\bin\coqc XRaxioms.v

XRbase.vo : XRbase.v  XRdefinitions.vo XRaxioms.vo XRIneq.vo XDiscrR.vo
	 C:\Coq\bin\coqc XRbase.v

XRbasic_fun.vo : XRbasic_fun.v  XRbase.vo XR_Ifp.vo
	 C:\Coq\bin\coqc XRbasic_fun.v

XRcomplete.vo : XRcomplete.v  XRbase.vo XRfunctions.vo XRseries.vo XSeqProp.vo
	 C:\Coq\bin\coqc XRcomplete.v

XRcompleteness.vo : XRcompleteness.v  XRaxioms.vo
	 C:\Coq\bin\coqc XRcompleteness.v

XRdefinitions.vo : XRdefinitions.v 
	 C:\Coq\bin\coqc XRdefinitions.v

XRderiv.vo : XRderiv.v  XRbase.vo XRfunctions.vo XRlimit.vo
	 C:\Coq\bin\coqc XRderiv.v

XReals.vo : XReals.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo.vo XRanalysis.vo XIntegration.vo
	 C:\Coq\bin\coqc XReals.v

XRfunctions.vo : XRfunctions.v  XRbase.vo XRpow_def.vo XR_Ifp.vo XRbasic_fun.vo XR_sqr.vo XSplitAbsolu.vo XSplitRmult.vo XArithProp.vo
	 C:\Coq\bin\coqc XRfunctions.v

XRgeom.vo : XRgeom.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XR_sqrt.vo
	 C:\Coq\bin\coqc XRgeom.v

XRiemannInt.vo : XRiemannInt.v  XRfunctions.vo XSeqSeries.vo XRanalysis_reg.vo XRbase.vo XRiemannInt_SF.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XRiemannInt.v

XRiemannInt_SF.vo : XRiemannInt_SF.v  XRbase.vo XRfunctions.vo XRanalysis_reg.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XRiemannInt_SF.v

XRIneq.vo : XRIneq.v  XRaxioms.vo XRpow_def.vo XRnumbers.vo XRNlink.vo XRRle_refl.vo XRRlt_irrefl.vo
	 C:\Coq\bin\coqc XRIneq.v

XRlimit.vo : XRlimit.v  XRbase.vo XRfunctions.vo
	 C:\Coq\bin\coqc XRlimit.v

XRList.vo : XRList.v  XRbase.vo XRfunctions.vo
	 C:\Coq\bin\coqc XRList.v

XRlogic.vo : XRlogic.v  XRIneq.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XRlogic.v

XRminmax.vo : XRminmax.v  XRbase.vo XRbasic_fun.vo XROrderedType.vo
	 C:\Coq\bin\coqc XRminmax.v

XRNlink.vo : XRNlink.v  XRdefinitions.vo
	 C:\Coq\bin\coqc XRNlink.v

XRnumbers.vo : XRnumbers.v  XRdefinitions.vo
	 C:\Coq\bin\coqc XRnumbers.v

XROrderedType.vo : XROrderedType.v  XRbase.vo
	 C:\Coq\bin\coqc XROrderedType.v

XRpower.vo : XRpower.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XRanalysis1.vo XExp_prop.vo XRsqrt_def.vo XR_sqrt.vo XSqrt_reg.vo XMVT.vo XRanalysis4.vo
	 C:\Coq\bin\coqc XRpower.v

XRpow_def.vo : XRpow_def.v  XRdefinitions.vo
	 C:\Coq\bin\coqc XRpow_def.v

XRprod.vo : XRprod.v  XRbase.vo XRfunctions.vo XRseries.vo XPartSum.vo XBinomial.vo
	 C:\Coq\bin\coqc XRprod.v

XRRle_refl.vo : XRRle_refl.v  XRaxioms.vo
	 C:\Coq\bin\coqc XRRle_refl.v

XRRlt_irrefl.vo : XRRlt_irrefl.v  XRaxioms.vo
	 C:\Coq\bin\coqc XRRlt_irrefl.v

XRseries.vo : XRseries.v  XRbase.vo XRfunctions.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XRseries.v

XRsigma.vo : XRsigma.v  XRbase.vo XRfunctions.vo XRseries.vo XPartSum.vo
	 C:\Coq\bin\coqc XRsigma.v

XRsqrt_def.vo : XRsqrt_def.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRanalysis1.vo
	 C:\Coq\bin\coqc XRsqrt_def.v

XRtopology.vo : XRtopology.v  XRbase.vo XRfunctions.vo XRanalysis1.vo XRList.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XRtopology.v

XRtrigo.vo : XRtrigo.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_fun.vo XRtrigo_def.vo XRtrigo_alt.vo XCos_rel.vo XCos_plus.vo XRanalysis1.vo XRsqrt_def.vo XPSeries_reg.vo XRtrigo1.vo XRatan.vo XMachin.vo
	 C:\Coq\bin\coqc XRtrigo.v

XRtrigo1.vo : XRtrigo1.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_fun.vo XRtrigo_def.vo XRtrigo_alt.vo XCos_rel.vo XCos_plus.vo XRanalysis1.vo XRsqrt_def.vo XPSeries_reg.vo
	 C:\Coq\bin\coqc XRtrigo1.v

XRtrigo_alt.vo : XRtrigo_alt.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_def.vo
	 C:\Coq\bin\coqc XRtrigo_alt.v

XRtrigo_calc.vo : XRtrigo_calc.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XR_sqrt.vo
	 C:\Coq\bin\coqc XRtrigo_calc.v

XRtrigo_def.vo : XRtrigo_def.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo_fun.vo
	 C:\Coq\bin\coqc XRtrigo_def.v

XRtrigo_fun.vo : XRtrigo_fun.v  XRbase.vo XRfunctions.vo XSeqSeries.vo
	 C:\Coq\bin\coqc XRtrigo_fun.v

XRtrigo_reg.vo : XRtrigo_reg.v  XRbase.vo XRfunctions.vo XSeqSeries.vo XRtrigo1.vo XRanalysis1.vo XPSeries_reg.vo
	 C:\Coq\bin\coqc XRtrigo_reg.v

XRZlink.vo : XRZlink.v  XRdefinitions.vo
	 C:\Coq\bin\coqc XRZlink.v

XR_Ifp.vo : XR_Ifp.v  XRbase.vo
	 C:\Coq\bin\coqc XR_Ifp.v

XR_sqr.vo : XR_sqr.v  XRbase.vo XRbasic_fun.vo
	 C:\Coq\bin\coqc XR_sqr.v

XR_sqrt.vo : XR_sqrt.v  XRbase.vo XRfunctions.vo XRsqrt_def.vo
	 C:\Coq\bin\coqc XR_sqrt.v

XSeqProp.vo : XSeqProp.v  XRbase.vo XRfunctions.vo XRseries.vo XRcompleteness.vo
	 C:\Coq\bin\coqc XSeqProp.v

XSeqSeries.vo : XSeqSeries.v  XRbase.vo XRfunctions.vo XRseries.vo XSeqProp.vo XRcomplete.vo XPartSum.vo XAltSeries.vo XBinomial.vo XRsigma.vo XRprod.vo XCauchy_prod.vo XAlembert.vo
	 C:\Coq\bin\coqc XSeqSeries.v

XSplitAbsolu.vo : XSplitAbsolu.v  XRbasic_fun.vo
	 C:\Coq\bin\coqc XSplitAbsolu.v

XSplitRmult.vo : XSplitRmult.v  XRbase.vo
	 C:\Coq\bin\coqc XSplitRmult.v

XSqrt_reg.vo : XSqrt_reg.v  XRbase.vo XRfunctions.vo XRanalysis1.vo XR_sqrt.vo
	 C:\Coq\bin\coqc XSqrt_reg.v

