Require Import XRbase.
Require Import XRfunctions.
Require Import XSeqSeries.
Require Export XRtrigo_fun.
Require Export XRtrigo_def.
Require Export XRtrigo_alt.
Require Export XCos_rel.
Require Export XCos_plus.
Require Import ZArith_base.
Require Import Zcomplements.
Require Import Fourier.
Require Import Ranalysis1.
Require Import Rsqrt_def. 
Require Import PSeries_reg.
Require Export Rtrigo1.
Require Export Ratan.
Require Export Machin.
