Require Import XRbase.
Require Import XRfunctions.
Require Import XRtrigo.
Require Import XSeqSeries.
Require Export XRanalysis1.
Require Export XRanalysis2.
Require Export XRanalysis3.
Require Export XRtopology.
Require Export XMVT.
Require Export XPSeries_reg.
Require Export XExp_prop.
Require Export XRtrigo_reg.
Require Export XRsqrt_def.
Require Export XR_sqrt.
Require Export XRtrigo_calc.
Require Export XRgeom.
Require Export XRList.
Require Export XSqrt_reg.
Require Export XRanalysis4.
Require Export XRpower.
Require Export XRanalysis_reg.
