Require Import XRbase.
Require Import XRfunctions.
Require Import XSeqSeries.
Require Export XRtrigo_fun.
Require Export XRtrigo_def.
Require Export XRtrigo_alt.
Require Export XCos_rel.
Require Export XCos_plus.
Require Import ZArith_base.
Require Import Zcomplements.
Require Import XRanalysis1.
Require Import XRsqrt_def. 
Require Import XPSeries_reg.
Require Export XRtrigo1.
Require Export XRatan.
Require Export XMachin.
